#!/bin/bash

imageURL=https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
imageName="jammy-server-cloudimg-amd64.img"
volumeName="local-lvm"
vmid="777"
templateName="jammy-tpl"
tmp_cores="2"
tmp_memory="2048"
rootPasswd="Letmein123"
cpuTypeRequired="qemu64"

apt update && apt install libguestfs-tools -y
qm destroy $vmid
wget -O $imageName $imageURL
virt-customize -a $imageName --install cloud-init,cloud-guest-utils,qemu-guest-agent,openssh-server,python3,resolvconf
virt-customize -a $imageName --root-password password:$rootPasswd
virt-customize -a $imageName --run-command 'apt-get clean && apt -y autoremove --purge && apt -y clean && apt -y autoclean'
virt-customize -a $imageName --run-command 'cloud-init clean && echo -n > /etc/machine-id && echo -n > /var/lib/dbus/machine-id && sync'
qm create $vmid --name $templateName --memory $tmp_memory --cores $tmp_cores --net0 virtio,bridge=vmbr0
qm importdisk $vmid $imageName $volumeName
qm set $vmid --scsihw virtio-scsi-single --scsi0 $volumeName:vm-$vmid-disk-0,cache=writeback,discard=on,ssd=1
qm set $vmid --boot c --bootdisk scsi0
qm set $vmid --ide2 $volumeName:cloudinit
qm set $vmid --serial0 socket --vga serial0
qm set $vmid --cicustom "user=local:snippets/cloudinit-jammy.yaml,network=local:snippets/cloudinit-network.yaml"
qm set $vmid --sshkeys /root/cloud/authorized_keys
qm set $vmid --cpu cputype=$cpuTypeRequired
qm set $vmid --ostype l26
qm set $vmid --balloon 2048
qm set $vmid --ciupgrade 1
qm set $vmid --ciuser ubuntu
qm set $vmid --ipconfig0 ip=dhcp
qm template $vmid
rm -f $imageName
