#cloud-config
package_update: true
package_upgrade: true

hostname: centos8

ssh:
  install-server: true
  allow-pw: true
  disable_root: false
  ssh_quiet_keygen: true
  allow_public_ssh_keys: true
chpasswd:
  expire: False

users:
  - name: ansible
    gecos: ansible
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: adm, users, sudo, docker
    lock_passwd: false
    passwd: $y$j9T$BHReuNpL9fry0wKeNhXvK.$OMQakqQs0Y/Rp9EUXrCYMGx5w0C9FIHdh6aJvWNOLx9:20563:0:99999:7:::
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPyYqXo0dEuiy5vBGQYIy/+FKaS22UEdUs+GYPDbrgsl
  - name: root
    lock_passwd: false
    passwd: $y$j9T$BHReuNpL9fry0wKeNhXvK.$OMQakqQs0Y/Rp9EUXrCYMGx5w0C9FIHdh6aJvWNOLx9:20563:0:99999:7:::

# Run commands on first boot
runcmd:
  - systemctl enable cloud-init-local.service
  - systemctl enable cloud-init.service
  - systemctl enable cloud-config.service
  - systemctl enable cloud-final.service
  - systemctl start cloud-init.service
  - systemctl start cloud-init-local.service
  - systemctl start cloud-config.service
  - systemctl start cloud-final.service
  - systemctl enable qemu-guest-agent --now
  - systemctl start qemu-guest-agent
  - systemctl enable resolvconf
  - systemctl disable systemd-resolved
  - systemctl mask systemd-resolved

